version: '1.1'
services:
  user_service:
    image: superpumpkin/iconnect_service:1.2.1
    command: ["npm", "run", "start:dev", "user"]
    container_name: user_service
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - iConnect_network

  auth_service:
    image: superpumpkin/iconnect_service:1.2.1
    command: ["npm", "run", "start:dev", "auth"]
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - iConnect_network

  transaction_service:
    image: superpumpkin/iconnect_service:1.2.1
    command: ["npm", "run", "start:dev", "area"]
    container_name: transaction_service
    env_file:
      - .env
    ports:
      - 8082:8082
    networks:
      - iConnect_network

  database_service:
    image: superpumpkin/iconnect_database:1.0.1
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: database_service
    volumes:
      - iConnect_db:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - iConnect_network

volumes:
  iConnect_db:

networks:
  iConnect_network:
