apiVersion: v1
kind: Service
metadata:
  name: area_service
  namespace: default
  labels:
    app: iConnect_Api
spec:
  selector:
    app: iConnect_Api
    tier: area_service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 8082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth_service
  labels:
    app: iConnect_Api
spec:
  selector:
    matchLabels:
      app: iConnect_Api
      tier: area_service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iConnect_Api
        tier: area_service
    spec:
      containers:
      - image: superpumpkin/iconnect_service:1.0.2
        name: area_service
        ports:
        - containerPort: 8082
        resources:
          request:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
