apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: iconnect_api
spec:
  selector:
    app: iconnect_api
    tier: auth-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - port: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: iconnect_api
spec:
  selector:
    matchLabels:
      app: iconnect_api
      tier: auth-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iconnect_api
        tier: auth-service
    spec:
      containers:
        - image: superpumpkin/iconnect_service:1.1.0
          name: auth-service
          command: ["npm", "run", "start:dev", "auth"]
          env:
            - name: JWT_SECRET
              value: "8efc953e5129a721a0c29bab50e8f06d828f4e74155b4d38104014737213d818"
            - name: JWT_EXPIRATION
              value: "10800"
            - name: host
              value: "iconnect-database"
            - name: port
              value: "3306"
            - name: username
              value: "backend"
            - name: password
              value: "P@ssw0rd"
            - name: database
              value: "iConnect"
            - name: ENCRYPT_SALT
              value: "4d00e4b03f3ce37883e8acfe1680b2aee4f68cfcc5c86e994308208e6531c70e"
            - name: UPLOAD_LOCATION
              value: "./apps/auth/src/news/images"
            - name: MAX_FILE_SIZE
              value: "5"
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
