apiVersion: v1
kind: Service
metadata:
  name: iconnect-database
  namespace: default
  labels:
    app: iconnect_api
spec:
  selector:
    app: iconnect_api
    tier: mysql
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - port: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iconnect-database
  labels:
    app: iconnect_api
spec:
  selector:
    matchLabels:
      app: iconnect_api
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iconnect_api
        tier: mysql
    spec:
      containers:
        - name: iconnect-database
          image: superpumpkin/iconnect_database:1.0.1
          env:
            - name: MYSQL_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: username
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: iconnect-database
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
              name: mysql
