apiVersion: v1
kind: Service
metadata:
  name: iConnect-database
spec:
  selector:
    app: iConnect-database
  ports:
    - port: 3307
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iConnect-database
spec:
  selector:
    matchLabels:
      app: iConnect-database
  template:
    metadata:
      labels:
        app: iConnect-database
    spec:
      containers:
        - name: iConnect-database
          image: mysql:8.1
          command:
            ["mysql", "--default-authentication-plugin=caching_sha2_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /var/lib/mysql  

